spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cars_controll
    username: tcc
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


